SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND SPECIFIC_NAME = 'Address_Delete')
	BEGIN
		DROP PROC Address_Delete
	END
GO
CREATE PROCEDURE Address_Delete
	@StudentId INT
AS
BEGIN
	SET NOCOUNT ON;
	DELETE FROM Addresses
	WHERE StudentId=@StudentId
END
GO
