SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND SPECIFIC_NAME = 'Address_Insert')
	BEGIN
		DROP PROC Address_Insert
	END
GO
CREATE PROCEDURE Address_Insert
	@StudentId INT,
	@Streeet NVARCHAR(30),
	@City NVARCHAR(20),
	@County NVARCHAR(20)
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO Addresses (StudentId, Streeet, City, County)
	VALUES (@StudentId, @Streeet, @City, @County)
END
GO
