SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.ROUTINES WHERE ROUTINE_TYPE = 'PROCEDURE' AND SPECIFIC_NAME = 'Students_Get')
	BEGIN
		DROP PROC Students_Get
	END
GO
CREATE PROCEDURE Students_Get
AS
BEGIN
	SET NOCOUNT ON;
	SELECT * FROM Students
	INNER JOIN Addresses
	ON Id = StudentId
END
GO
